general:
  seed: 1
  task_type: "joint" # classification, regression, joint
  classes_num: 6 # 24 + silence
  model_name: "resnest14d"
  use_additional_loss_for_aam: True
  device_ids: [0]
  out_path: "./IDAO_2021_oski/experiments/resnest14d_1e-4_joint_/"
  data_root: "/media/paniquex/samsung_2tb/IDAO_2021_oski/data/track_1/idao_dataset"
  early_stopping_by: "comp_metric" # f1, roc_auc, mae, comp_metric

preprocessing:
  img_size: [224, 224]

pseudo:
  iter: 5
  n_epochs: 10
  n_epochs_flat: 3
  lr_coef : 0.5
  reg_postprocessing: False
  threshold: 0.95


training:
  loss:
    clf: "BCE"
    reg: "L1" # "L1" - regression, "AAM" "BCE", "FOCAL" - classification
  activation_func: ReLU # ReLU, Mish
  n_epochs: 15
  n_epochs_flat: 5
  early_stopping_criterion: 5
  n_folds: 3
  logging_freq: 1
  lr: !!float 1e-4
  finetune: False
  models_dir: "" # Directory with pretrained models
  # augmentations: {} #dict with aug name: params mapping #TODO

  # dataset config
  #dataset: TODO

  # dataloader config
  dataloader:
    batch_size: 32
    shuffle: True
    num_workers: 8
    pin_memory: False
    drop_last: True

validation:
#  augmentations: {} TODO

#  dataset:  TODO

  # dataloader config
  dataloader:
    batch_size: 24
    shuffle: False
    num_workers: 4
    pin_memory: False


testing:
#  augmentations: {} TODO
  models_dir: "/media/paniquex/samsung_2tb/IDAO_2021_oski/experiments/check_experiment/" # directory with pretrained models
#  dataset: TODO

  dataloader:
    batch_size: 16
    shuffle: False
    num_workers: 4
    pin_memory: True
